title: BOUN Sociolinguistics Language Contact Project
description: Greek and Turkish in Contact
author: Konstantinos Sampanis
email: konstantinos {dot} sampanis {at} boun {dot} edu {dot} tr  
github: https://github.com/BounSocLing
about: We are a group of people who are interested in language contact between Greek and Turkish and how it plays out in morphosyntactic frame.
phone: +90 212 359 49 09
#disqus_shortname: linguistics
#google_analytics: 
avatar_url: /static/img/me.jpeg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    #- icon: fa-facebook
    #  link: "https://www.facebook.com/tjamadar"
    - icon: fa-twitter
      link: "https://twitter.com/theutkuturk"
    #- icon: fa-linkedin
    #  link: "https://www.linkedin.com/in/tauseef-jamadar-5b577913/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/BounSocLing"

share:
  twitter_username: theutkuturk
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://BounSocLing.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
